
var CENTRES = { 
  "annapolis": "annapolis",
  "brandon": "brandon",
  "broward": "broward",
  "century city": "centurycity",
  "citrus park": "citruspark",
  "countryside": "countryside",
  "culver city": "culvercity",
  "fashion square": "fashionsquare",
  "galleria at roseville": "galleriaatroseville",
  "galleria roseville": "galleriaatroseville",
  "galleria": "galleriaatroseville",
  "roseville": "galleriaatroseville",
  "roseville galleria": "galleriaatroseville",
  "garden state plaza": "gardenstateplaza",
  "garden state": "gardenstateplaza",
  "horton plaza": "hortonplaza",
  "horton": "hortonplaza",
  "meriden": "meriden",
  "mission valley": "missionvalley",
  "montgomery": "montgomery",
  "north county": "northcounty",
  "oakridge": "oakridge",
  "old orchard": "oldorchard",
  "palm desert": "palmdesert",
  "plaza bonita": "plazabonita",
  "san francisco": "sanfrancisco",
  "san francisco centre": "sanfrancisco",
  "santa anita": "santaanita",
  "sarasota square": "sarasota",
  "southcenter": "southcenter",
  "southgate": "southgate",
  "south shore": "southshore",
  "sunrise": "sunrise",
  "topanga and the village": "topanga",
  "topanga": "topanga",
  "trumbull": "trumbull",
  "utc": "utc",
  "valencia town center": "valencia",
  "valley fair": "valleyfair",
  "wheaton": "wheaton",
  "world trade center": "westfieldworldtradecenter",
  "world trade": "westfieldworldtradecenter" 
};

var CENTRE_NAMES = [
  "annapolis",
  "brandon",
  "broward",
  "century city",
  "citrus park",
  "countryside",
  "culver city",
  "fashion square",
  "galleria at roseville",
  "garden state plaza",
  "horton plaza",
  "horton",
  "meriden",
  "mission valley",
  "montgomery",
  "north county",
  "oakridge",
  "old orchard",
  "palm desert",
  "plaza bonita",
  "san francisco centre",
  "santa anita",
  "sarasota square",
  "southcenter",
  "southgate",
  "south shore",
  "sunrise",
  "topanga and the village",
  "trumbull",
  "utc",
  "valencia town center",
  "valley fair",
  "wheaton",
  "world trade center"
];

module.exports = {
  CENTRE_NAMES: CENTRE_NAMES,
  CENTRES: CENTRES
}
